spring:
  application:
    name: ollama-gate
  datasource:
    url: jdbc:h2:file:./ollama-gate-data
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
llama:
  url: ${LLAMA_URL:http://localhost:11434}
springdoc:
  api-docs:
    enabled: true
    path: /ollama-api
  swagger-ui:
    path: /swagger